### PR TITLE
[FIX] duplicate product.template

### PR DESCRIPTION
**Pull request by PierrickBrun**
if the create is called via a non-empty recordset, this will not behave like intended

### CODE REVIEW

**Comment by PierrickBrun** [comment]
@legalsylvain can you include this fix in your PR ?

**Comment by legalsylvain** [comment]
could you rebase @PierrickBrun ?

**Comment by PierrickBrun** [comment]
done

**Comment by PierrickBrun** [comment]
ping

**Comment by PierrickBrun** [comment]
@legalsylvain please include this with https://github.com/legalsylvain/stock-logistics-barcode/pull/4 :smile:

**Comment by legalsylvain** [comment]
Hi @PierrickBrun. Totally sorry for the late. I merged #4 just right now.

for your patch, I'm asking if we should not use the new design. Something like : 

(https://github.com/odoo/odoo/blob/16.0/addons/product/models/product_template.py#L422)

    def _get_related_fields_variant_template(self):
        """ Return a list of fields present on template and variants models and that are related"""
        res = super()_get_related_fields_variant_template()
        res.append(["barcode_base", barcode_rule_id"])
        return res

and maybe compute barcode_base + barcode_rule_id with the new way.

https://github.com/odoo/odoo/blob/16.0/addons/product/models/product_template.py#L217

What do you think ?

**Pull request closed without merging**
